import NavBar from "../components/NavBar"

export const metadata = {
  title: 'My Next.js',
  description: 'Generated by Gustavo Jimenez',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
        <NavBar/>
        {children}
      </body>
    </html>
  )
}
